### ISSUE TITLE
Twitter bot that tweets a color combination with a link to vote on it

### ISSUE THREAD

**Issue by johnotander** [johnotander/random-a11y#25]
Idea from @alexbaldwin

**Comment by lachlanjc** [comment]
I love this idea, but we need a few things for this.

1. A Twitter account with API access. ([@randoma11y](https://twitter.com/randoma11y) seems to have been registered in July 2016 — is that you @johnotander? 👀  Otherwise [@random_a11y](https://twitter.com/random_a11y) would work.)
2. A way to run background jobs. Maybe run it every 8 hours (3/day) or something? I know nothing about how to do this.
3. A script that generates a screenshot and the text and tweets it. This shouldn’t be too hard.

**Comment by johnotander** [comment]
1. That's me : ). I'll message you credentials.
2. We can set that up on heroku using the heroku scheduler.
3. Yep, absolutely.

One other thing is we will need to be able to specify to hex colors via the query param. Currently you can only specify `?hex=fff`. So we could do something like `?hex=fff&compare=444` or something so that the link will result in the comparison between the two tweeted colors.

**Comment by lachlanjc** [comment]
1. Awesome on the Twitter. We need an avatar. I’ll make an issue.
2. I’ll look into how exactly all that works re: Heroku scheduler. Maybe add me as a collaborator to the Heroku app?
3. Yep, good thinking. Another issue :)

**Comment by johnotander** [comment]
Completed thanks to the hard work from @alexbaldwin: https://twitter.com/a11ycolors

**Comment by lachlanjc** [comment]
🙌🏻👏🏻
